# Generated by Django 3.0.5 on 2021-02-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(default='', max_length=70)),
                ('article_price_original', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency_original', models.CharField(default='', max_length=5)),
                ('supermarket', models.CharField(default='', max_length=70)),
                ('article_price_calculated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency_calculated', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
