# Generated by Django 3.0.5 on 2021-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='bio',
            field=models.BooleanField(default=False),
        ),
    ]
