# Generated by Django 3.0.5 on 2021-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shopping_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='article_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
